# Generated by Django 6.0.5 on 2026-05-08 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_id", models.CharField(max_length=40, unique=True)),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("PARCEL_PHOTO", "包裹图片"),
                            ("REMITTANCE_PROOF", "汇款凭证"),
                            ("MESSAGE_ATTACHMENT", "消息附件"),
                            ("PRODUCT_IMAGE", "商品图片"),
                            ("CONTENT_IMAGE", "内容图片"),
                            ("PURCHASE_PROOF", "采购凭证"),
                            ("IMPORT_FILE", "导入文件"),
                            ("GENERAL", "通用文件"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[("MEMBER", "会员"), ("ADMIN", "后台")], max_length=20
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("storage_key", models.CharField(max_length=255, unique=True)),
                ("content_type", models.CharField(max_length=120)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("extension", models.CharField(max_length=20)),
                ("checksum_sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "启用"), ("DELETED", "已删除")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_files",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "uploaded_by_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_files",
                        to="members.user",
                    ),
                ),
            ],
            options={
                "db_table": "files",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["owner_type", "status"], name="idx_files_owner_status"
                    ),
                    models.Index(
                        fields=["usage", "status"], name="idx_files_usage_status"
                    ),
                ],
            },
        ),
    ]
