# Generated by Django 6.0.5 on 2026-05-09 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ANNOUNCEMENT", "公告"),
                            ("HELP", "帮助"),
                            ("TERMS", "服务条款"),
                            ("PRIVACY", "隐私政策"),
                            ("ABOUT", "关于我们"),
                        ],
                        default="HELP",
                        max_length=30,
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "启用"), ("DISABLED", "停用")],
                        default="ACTIVE",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "content_categories",
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["type", "status", "sort_order"],
                        name="idx_content_cat_type_status",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ANNOUNCEMENT", "公告"),
                            ("HELP", "帮助"),
                            ("TERMS", "服务条款"),
                            ("PRIVACY", "隐私政策"),
                            ("ABOUT", "关于我们"),
                        ],
                        default="HELP",
                        max_length=30,
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("PUBLISHED", "已发布"),
                            ("HIDDEN", "已隐藏"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pages",
                        to="content.contentcategory",
                    ),
                ),
                (
                    "created_by_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_content_pages",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "updated_by_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_content_pages",
                        to="iam.adminuser",
                    ),
                ),
            ],
            options={
                "db_table": "content_pages",
                "ordering": ["type", "sort_order", "-published_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["type", "status", "sort_order"],
                        name="idx_content_pg_type_status",
                    ),
                    models.Index(
                        fields=["category", "status"],
                        name="idx_content_pg_cat_status",
                    ),
                ],
            },
        ),
    ]
