# Generated by Django 6.0.5 on 2026-05-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=180)),
                ("target_type", models.CharField(max_length=120)),
                ("target_id", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待审批"),
                            ("APPROVED", "已通过"),
                            ("REJECTED", "已驳回"),
                            ("EXPIRED", "已过期"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("requester_id", models.PositiveBigIntegerField()),
                ("requester_label", models.CharField(blank=True, max_length=160)),
                ("approver_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("approver_label", models.CharField(blank=True, max_length=160)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True)),
                ("decision_note", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "approval_requests",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["status"], name="idx_approval_status"),
                    models.Index(fields=["action"], name="idx_approval_action"),
                    models.Index(
                        fields=["requester_id"], name="idx_approval_requester"
                    ),
                ],
            },
        ),
    ]
