# Generated by Django 6.0.5 on 2026-05-08 15:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_no", models.CharField(max_length=30, unique=True)),
                (
                    "business_type",
                    models.CharField(
                        choices=[("WAYBILL", "运单"), ("PURCHASE_ORDER", "代购单")],
                        max_length=30,
                    ),
                ),
                ("business_id", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待支付"),
                            ("PROCESSING", "支付处理中"),
                            ("PAID", "已支付"),
                            ("FAILED", "支付失败"),
                            ("CANCELLED", "已取消"),
                            ("REFUNDED", "已退款"),
                            ("PARTIAL_REFUNDED", "部分退款"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="CNY", max_length=10)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                ("remark", models.CharField(blank=True, max_length=255)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_orders",
                        to="members.user",
                    ),
                ),
            ],
            options={
                "db_table": "payment_orders",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="CNY", max_length=10)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "frozen_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallets",
                        to="members.user",
                    ),
                ),
            ],
            options={
                "db_table": "wallets",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RechargeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_no", models.CharField(max_length=30, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="CNY", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "已完成"), ("CANCELLED", "已取消")],
                        default="COMPLETED",
                        max_length=30,
                    ),
                ),
                ("remark", models.CharField(blank=True, max_length=255)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recharge_requests",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recharge_requests",
                        to="members.user",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recharge_requests",
                        to="finance.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "recharge_requests",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ADMIN_RECHARGE", "后台充值"),
                            ("ADMIN_DEDUCT", "后台扣减"),
                            ("WAYBILL_PAYMENT", "运费支付"),
                            ("PURCHASE_PAYMENT", "代购支付"),
                            ("REFUND", "退款"),
                            ("ADJUSTMENT", "余额调整"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("INCREASE", "增加"), ("DECREASE", "减少")],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                ("business_type", models.CharField(blank=True, max_length=30)),
                ("business_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet_transactions",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "payment_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet_transactions",
                        to="finance.paymentorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet_transactions",
                        to="members.user",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finance.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_transactions",
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="paymentorder",
            constraint=models.UniqueConstraint(
                fields=("business_type", "business_id"), name="uq_payment_business_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.UniqueConstraint(
                fields=("user", "currency"), name="uq_wallet_user_currency"
            ),
        ),
    ]
