# Generated by Django 6.0.5 on 2026-05-08 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rechargerequest",
            name="proof_file_id",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="rechargerequest",
            name="review_remark",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="rechargerequest",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rechargerequest",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recharge_requests",
                to="iam.adminuser",
            ),
        ),
        migrations.AlterField(
            model_name="rechargerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "待审核"),
                    ("COMPLETED", "已完成"),
                    ("CANCELLED", "已取消"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("ADMIN_RECHARGE", "后台充值"),
                    ("ADMIN_DEDUCT", "后台扣减"),
                    ("OFFLINE_REMITTANCE", "线下汇款"),
                    ("WAYBILL_PAYMENT", "运费支付"),
                    ("PURCHASE_PAYMENT", "代购支付"),
                    ("REFUND", "退款"),
                    ("ADJUSTMENT", "余额调整"),
                ],
                max_length=30,
            ),
        ),
    ]
