# Generated by Django 6.0.5 on 2026-05-08 12:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0001_initial"),
        ("members", "0001_initial"),
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parcel_no", models.CharField(max_length=30, unique=True)),
                ("tracking_no", models.CharField(max_length=80, unique=True)),
                ("carrier", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_INBOUND", "待入库"),
                            ("IN_STOCK", "在库"),
                            ("PACKING_REQUESTED", "已申请打包"),
                            ("PACKED", "已打包"),
                            ("OUTBOUND", "已出库"),
                            ("CANCELLED", "已取消"),
                            ("PROBLEM", "问题包裹"),
                        ],
                        default="PENDING_INBOUND",
                        max_length=30,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "length_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "width_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("remark", models.TextField(blank=True)),
                ("inbound_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcels",
                        to="members.user",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcels",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "parcels",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="InboundRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_kg", models.DecimalField(decimal_places=3, max_digits=10)),
                ("dimensions_json", models.JSONField(blank=True, default=dict)),
                ("remark", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_records",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_records",
                        to="parcels.parcel",
                    ),
                ),
            ],
            options={
                "db_table": "inbound_records",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ParcelItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "declared_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("product_url", models.URLField(blank=True)),
                ("remark", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="parcels.parcel",
                    ),
                ),
            ],
            options={
                "db_table": "parcel_items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ParcelPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_id", models.CharField(max_length=120)),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("INBOUND", "入库"),
                            ("DAMAGE", "破损"),
                            ("OTHER", "其他"),
                        ],
                        default="INBOUND",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="parcels.parcel",
                    ),
                ),
            ],
            options={
                "db_table": "parcel_photos",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="UnclaimedParcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_no", models.CharField(max_length=80, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNCLAIMED", "待认领"),
                            ("CLAIM_PENDING", "认领待审"),
                            ("CLAIMED", "已认领"),
                        ],
                        default="UNCLAIMED",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("dimensions_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claimed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claimed_unclaimed_parcels",
                        to="members.user",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unclaimed_parcels",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "unclaimed_parcels",
                "ordering": ["-id"],
            },
        ),
    ]
