# Generated by Django 6.0.5 on 2026-05-09 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
        ("parcels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unclaimedparcel",
            name="claim_contact",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="unclaimedparcel",
            name="claim_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unclaimedparcel",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unclaimedparcel",
            name="review_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unclaimedparcel",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unclaimedparcel",
            name="reviewed_by_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_unclaimed_parcels",
                to="iam.adminuser",
            ),
        ),
    ]
