# Generated by Django 6.0.5 on 2026-05-09 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_memberprofile_assigned_service_admin_and_more"),
        ("parcels", "0002_unclaimedparcel_claim_contact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParcelImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_no", models.CharField(max_length=30, unique=True)),
                ("file_id", models.CharField(max_length=120)),
                ("original_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "已完成"), ("FAILED", "失败")],
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("errors_json", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcel_import_jobs",
                        to="members.user",
                    ),
                ),
            ],
            options={
                "db_table": "parcel_import_jobs",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="idx_parcel_import_user_status"
                    ),
                    models.Index(fields=["file_id"], name="idx_parcel_import_file_id"),
                ],
            },
        ),
    ]
