# Generated by Django 6.0.5 on 2026-05-08 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="assigned_service_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_member_profiles",
                to="iam.adminuser",
            ),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="service_note",
            field=models.TextField(blank=True),
        ),
    ]
