# Generated by Django 6.0.5 on 2026-05-09 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
        ("members", "0002_memberprofile_assigned_service_admin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invitation_code", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待确认"),
                            ("ACTIVE", "有效"),
                            ("INVALID", "无效"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("remark", models.CharField(blank=True, max_length=255)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_referral_relations",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invited_by_relations",
                        to="members.user",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referral_invites",
                        to="members.user",
                    ),
                ),
            ],
            options={
                "db_table": "referral_relations",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="RebateRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("reward_points", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="CNY", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待确认"),
                            ("CONFIRMED", "已确认"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("business_type", models.CharField(blank=True, max_length=50)),
                ("business_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_rebate_records",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rebate_records",
                        to="members.user",
                    ),
                ),
                (
                    "referral_relation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rebate_records",
                        to="members.referralrelation",
                    ),
                ),
            ],
            options={
                "db_table": "rebate_records",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PointLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "注册赠送"),
                            ("MANUAL_ADJUSTMENT", "后台调整"),
                            ("ORDER_REWARD", "订单奖励"),
                            ("REBATE_REWARD", "返利奖励"),
                            ("EXCHANGE_HOLD", "兑换占位"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("EARN", "获得"), ("SPEND", "扣减")], max_length=20
                    ),
                ),
                ("points", models.PositiveIntegerField()),
                ("balance_after", models.PositiveIntegerField(default=0)),
                ("business_type", models.CharField(blank=True, max_length=50)),
                ("business_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="point_ledgers",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="point_ledgers",
                        to="members.user",
                    ),
                ),
            ],
            options={
                "db_table": "point_ledgers",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "-id"], name="idx_point_ledgers_user_id"
                    ),
                    models.Index(
                        fields=["business_type", "business_id"],
                        name="idx_point_ledgers_business",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="referralrelation",
            index=models.Index(
                fields=["inviter", "status"], name="idx_referral_inviter_status"
            ),
        ),
        migrations.AddIndex(
            model_name="referralrelation",
            index=models.Index(
                fields=["invitation_code"], name="idx_referral_invite_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="referralrelation",
            constraint=models.UniqueConstraint(
                fields=("invitee",), name="uq_referral_invitee_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="referralrelation",
            constraint=models.UniqueConstraint(
                fields=("inviter", "invitee"), name="uq_referral_inviter_invitee_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="referralrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("inviter_id", models.F("invitee_id")), _negated=True
                ),
                name="ck_referral_inviter_not_invitee",
            ),
        ),
        migrations.AddIndex(
            model_name="rebaterecord",
            index=models.Index(
                fields=["user", "status"], name="idx_rebate_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="rebaterecord",
            index=models.Index(
                fields=["business_type", "business_id"], name="idx_rebate_business"
            ),
        ),
    ]
