# Generated by Django 6.0.5 on 2026-05-09 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_referralrelation_rebaterecord_pointledger_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("requested_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to="members.user",
                    ),
                ),
            ],
            options={
                "db_table": "password_reset_tokens",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "expires_at"], name="idx_pwd_reset_user_expires"
                    ),
                    models.Index(fields=["token_hash"], name="idx_pwd_reset_hash"),
                ],
            },
        ),
    ]
