# Generated by Django 6.0.5 on 2026-05-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_password_reset_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
