from django.urls import path

from .views import (
    AdminPointLedgerListView,
    AdminRebateRecordListCreateView,
    AdminReferralRelationListCreateView,
    AdminMemberDetailView,
    AdminMemberFreezeView,
    AdminMemberGrowthDetailView,
    AdminMemberListView,
    AdminMemberResetPasswordView,
    AdminMemberUnfreezeView,
    AdminSupportUserListView,
    AdminUserPointAdjustView,
    GrowthSummaryView,
    MemberLoginView,
    MemberLogoutView,
    MePasswordView,
    MeProfileView,
    MeView,
    PointLedgerListView,
    RebateRecordListView,
    ReferralRelationListView,
    RegisterView,
)

urlpatterns = [
    path("auth/register", RegisterView.as_view(), name="member-register"),
    path("auth/login", MemberLoginView.as_view(), name="member-login"),
    path("auth/logout", MemberLogoutView.as_view(), name="member-logout"),
    path("me", MeView.as_view(), name="member-me"),
    path("me/profile", MeProfileView.as_view(), name="member-profile"),
    path("me/password", MePasswordView.as_view(), name="member-password"),
    path("growth/summary", GrowthSummaryView.as_view(), name="growth-summary"),
    path("growth/point-ledgers", PointLedgerListView.as_view(), name="growth-point-ledger-list"),
    path("growth/referrals", ReferralRelationListView.as_view(), name="growth-referral-list"),
    path("growth/rebates", RebateRecordListView.as_view(), name="growth-rebate-list"),
    path("admin/members", AdminMemberListView.as_view(), name="admin-members"),
    path("admin/members/<int:user_id>", AdminMemberDetailView.as_view(), name="admin-member-detail"),
    path("admin/members/<int:user_id>/growth", AdminMemberGrowthDetailView.as_view(), name="admin-member-growth-detail"),
    path("admin/members/<int:user_id>/freeze", AdminMemberFreezeView.as_view(), name="admin-member-freeze"),
    path("admin/members/<int:user_id>/unfreeze", AdminMemberUnfreezeView.as_view(), name="admin-member-unfreeze"),
    path(
        "admin/members/<int:user_id>/reset-password",
        AdminMemberResetPasswordView.as_view(),
        name="admin-member-reset-password",
    ),
    path("admin/member-service-admins", AdminSupportUserListView.as_view(), name="admin-member-service-admins"),
    path("admin/growth/point-ledgers", AdminPointLedgerListView.as_view(), name="admin-growth-point-ledger-list"),
    path("admin/growth/referrals", AdminReferralRelationListCreateView.as_view(), name="admin-growth-referral-list"),
    path("admin/growth/rebates", AdminRebateRecordListCreateView.as_view(), name="admin-growth-rebate-list"),
    path(
        "admin/members/<int:user_id>/points/adjust",
        AdminUserPointAdjustView.as_view(),
        name="admin-member-point-adjust",
    ),
]
