# Generated by Django 6.0.5 on 2026-05-09 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CountryRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "iso_code",
                    models.CharField(
                        blank=True, help_text="ISO 3166 alpha-2/3", max_length=10
                    ),
                ),
                (
                    "phone_code",
                    models.CharField(blank=True, help_text="国际区号", max_length=10),
                ),
                ("currency_code", models.CharField(blank=True, max_length=10)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("COUNTRY", "国家"),
                            ("PROVINCE", "省/州"),
                            ("CITY", "城市"),
                            ("DISTRICT", "区/县"),
                            ("ZONE", "区域"),
                        ],
                        default="COUNTRY",
                        max_length=20,
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="regions.countryregion",
                    ),
                ),
            ],
            options={
                "db_table": "country_regions",
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent", "name"), name="uq_region_parent_name"
                    )
                ],
            },
        ),
    ]
