# Generated by Django 6.0.5 on 2026-05-08 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_no", models.CharField(max_length=30, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "普通咨询"),
                            ("PARCEL", "包裹问题"),
                            ("WAYBILL", "运单问题"),
                            ("PURCHASE", "代购问题"),
                            ("FINANCE", "财务问题"),
                            ("ACCOUNT", "账号问题"),
                        ],
                        default="GENERAL",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "待处理"),
                            ("PROCESSING", "处理中"),
                            ("CLOSED", "已关闭"),
                        ],
                        default="OPEN",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handled_tickets",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="members.user",
                    ),
                ),
            ],
            options={
                "db_table": "tickets",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("MEMBER", "会员"), ("ADMIN", "后台")], max_length=20
                    ),
                ),
                ("content", models.TextField()),
                ("file_id", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_messages",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_messages",
                        to="members.user",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_messages",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["user", "status"], name="idx_tickets_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "updated_at"], name="idx_tickets_status_updated"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketmessage",
            index=models.Index(
                fields=["ticket", "created_at"], name="idx_ticket_messages_time"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketmessage",
            index=models.Index(fields=["file_id"], name="idx_ticket_messages_file"),
        ),
    ]
