# Generated by Django 6.0.5 on 2026-05-09 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "attr_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "文本"),
                            ("NUMBER", "数字"),
                            ("ENUM", "枚举"),
                            ("BOOLEAN", "布尔"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                ("is_filterable", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="绑定分类（为空则全局属性）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attributes",
                        to="products.productcategory",
                    ),
                ),
            ],
            options={
                "db_table": "product_attributes",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="products.productattribute",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_attribute_values",
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "attribute"), name="uq_product_attr"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(help_text="例如 zh-CN, en, ja", max_length=10),
                ),
                ("title", models.CharField(max_length=160)),
                ("description_rich", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_translations",
                "ordering": ["language_code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "language_code"), name="uq_product_lang"
                    )
                ],
            },
        ),
    ]
