# Generated by Django 6.0.5 on 2026-05-08 15:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0001_initial"),
        ("members", "0001_initial"),
        ("parcels", "0001_initial"),
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Waybill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("waybill_no", models.CharField(max_length=30, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "待审核"),
                            ("PENDING_PACKING", "待打包"),
                            ("PENDING_PAYMENT", "待付款"),
                            ("PENDING_SHIPMENT", "待发货"),
                            ("SHIPPED", "已发货"),
                            ("SIGNED", "已签收"),
                            ("CANCELLED", "已取消"),
                            ("PROBLEM", "问题单"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=30,
                    ),
                ),
                ("destination_country", models.CharField(max_length=80)),
                ("recipient_snapshot", models.JSONField(default=dict)),
                (
                    "fee_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("fee_detail_json", models.JSONField(blank=True, default=dict)),
                ("remark", models.TextField(blank=True)),
                ("review_remark", models.CharField(blank=True, max_length=255)),
                ("fee_remark", models.CharField(blank=True, max_length=255)),
                ("cancel_reason", models.CharField(blank=True, max_length=255)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("fee_set_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waybills",
                        to="warehouses.shippingchannel",
                    ),
                ),
                (
                    "fee_set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_set_waybills",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_waybills",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waybills",
                        to="members.user",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waybills",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "waybills",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="WaybillParcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waybill_links",
                        to="parcels.parcel",
                    ),
                ),
                (
                    "waybill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcel_links",
                        to="waybills.waybill",
                    ),
                ),
            ],
            options={
                "db_table": "waybill_parcels",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("waybill", "parcel"), name="uq_waybill_parcel_once"
                    )
                ],
            },
        ),
    ]
