# Generated by Django 6.0.5 on 2026-05-08 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
        ("waybills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_time", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=120)),
                ("status_text", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "人工"),
                            ("MEMBER", "会员"),
                            ("SYSTEM", "系统"),
                        ],
                        default="MANUAL",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tracking_events",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "waybill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="waybills.waybill",
                    ),
                ),
            ],
            options={
                "db_table": "tracking_events",
                "ordering": ["event_time", "id"],
            },
        ),
    ]
