# Generated by Django 6.0.5 on 2026-05-09 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
        ("warehouses", "0001_initial"),
        ("waybills", "0002_trackingevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="waybill",
            name="transfer_no",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name="ShippingBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_no", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("LOCKED", "已锁定"),
                            ("SHIPPED", "已发货"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("carrier_batch_no", models.CharField(blank=True, max_length=80)),
                ("transfer_no", models.CharField(blank=True, max_length=80)),
                ("ship_note", models.CharField(blank=True, max_length=255)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_shipping_batches",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locked_shipping_batches",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "shipped_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipped_shipping_batches",
                        to="iam.adminuser",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipping_batches",
                        to="warehouses.warehouse",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipping_batches",
                        to="warehouses.shippingchannel",
                    ),
                ),
            ],
            options={
                "db_table": "shipping_batches",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="waybill",
            name="shipping_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="waybills",
                to="waybills.shippingbatch",
            ),
        ),
    ]
